services:
  postgres_db:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_DB=spring_db
      - POSTGRES_USER=amarchuk
      - POSTGRES_PASSWORD=password
    ports:
      - "5435:5432"
